### ISSUE TITLE
Make MXQUEUE_LENGTH_LIMIT configure by param

### ISSUE THREAD

**Issue by stleon** [halturin/mx#2]
Now **MXQUEUE_LENGTH_LIMIT** is configured by changing the source file:
```
-define(MXQUEUE_LENGTH_LIMIT,       50000).
```
It will be cool to make this parameter configurable through environment variables or something else

**Comment by halturin** [comment]
there is an option (https://github.com/halturin/mx/blob/master/src/mx_mnesia.erl#L72), it uses env variable. so, we have to keep the same way

**Comment by stleon** [comment]
done in https://github.com/halturin/mx/pull/4
